repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: debug-statements
      - id: detect-private-key
      - id: check-merge-conflict
      - id: mixed-line-ending
      - id: check-executables-have-shebangs

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0
    hooks:
      - id: prettier
        additional_dependencies: ["prettier@3.0.0"]

  - repo: local
    hooks:
      - id: check-ignored-files
        name: Check ignored files are not committed
        entry: bash -c 'git ls-files -ci --exclude-standard | grep . && (echo "Error: Ignored files were committed" && exit 1) || exit 0'
        language: system
        types: [file]
