name: Update Architecture Map

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main, feature/** ]

jobs:
  update-architecture:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Generate architecture map
        run: |
          python scripts/generate_architecture.py

      - name: Commit updated architecture map
        run: |
          git config user.name "holly-bot"
          git config user.email "holly-bot@users.noreply.github.com"
          git add docs/architecture.md
          git commit -m "ci: auto-update architecture map [skip ci]" || echo "No changes to commit"
          git push